version: 2
plugins:
#  disabled before git-legal supports bundler 2 https://github.com/kmewhort/git.legal-codeclimate/issues/6
#  git-legal:
#    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-73
    config:
      file: ".rubocop.yml"
  bundler-audit:
    enabled: true
exclude_patterns:
  - "spec/"
  - "*.gemspec"
