AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'tmp/**/*'

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']